---
  - name: zebra install
    file: path=/home/koha-admin/zebrayaz state=directory

  - name: zebra
    get_url: url=http://ftp.indexdata.dk/pub/zebra/redhat/centos/7/RPMS/x86_64/{{item}}  dest=/home/koha-admin/zebrayaz/{{item}}
    with_items:
    - idzebra-2.0-2.1.3-1.indexdata.x86_64.rpm
    - libidzebra-2.0-2.1.3-1.indexdata.x86_64.rpm
    - libidzebra-2.0-modules-2.1.3-1.indexdata.x86_64.rpm
    - libidzebra-2.0-devel-2.1.3-1.indexdata.x86_64.rpm

  - name: yaz
    get_url: url=http://ftp.indexdata.dk/pub/yaz/redhat/centos/7/RPMS/x86_64/{{item}}  dest=/home/koha-admin/zebrayaz/{{item}}
    with_items:
    - libyaz5-5.23.1-1.indexdata.x86_64.rpm
    - libyaz5-devel-5.23.1-1.indexdata.x86_64.rpm
    - yaz-5.23.1-1.indexdata.x86_64.rpm

  - name: install idzebra
    yum:
     name: /home/koha-admin/zebrayaz/{{ item }}
    with_items:
    - idzebra-2.0-2.1.3-1.indexdata.x86_64.rpm
    - libidzebra-2.0-2.1.3-1.indexdata.x86_64.rpm
    - libidzebra-2.0-modules-2.1.3-1.indexdata.x86_64.rpm
    - libidzebra-2.0-devel-2.1.3-1.indexdata.x86_64.rpm
    - libyaz5-5.23.1-1.indexdata.x86_64.rpm
    - libyaz5-devel-5.23.1-1.indexdata.x86_64.rpm
    - yaz-5.23.1-1.indexdata.x86_64.rpm




